apiVersion: apps/v1
kind: Deployment
metadata:
  name: guestbook
  labels:
    app: guestbook
spec:
  replicas: 1
  selector:
    matchLabels:
      app: guestbook
  template:
    metadata:
      labels:
        app: guestbook
    spec:
      containers:
      - name: guestbook
        image: ibmcom/guestbook:v2
        ports:
        - name: guestbook-port
          containerPort: 3000
        env:
        - name: REDIS_MASTER_SERVICE_HOST
          valueFrom: 
            configMapKeyRef:
              name: guestbook
              key: redis_master_service_host
        - name: REDIS_MASTER_SERVICE_PORT
          valueFrom:
            configMapKeyRef:
              name: guestbook
              key: redis_master_service_port
        - name: REDIS_MASTER_PORT
          valueFrom:
            configMapKeyRef:
              name: guestbook
              key: redis_master_port
        - name: HOSTNAME
          valueFrom:
            configMapKeyRef:
              name: guestbook
              key: hostname
        - name: REDIS_MASTER_SERVICE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: guestbook
              key: redis_master_service_password